# Generated by Django 5.0.4 on 2024-04-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured ?'),
        ),
        migrations.CreateModel(
            name='BookOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
            ],
            options={
                'verbose_name_plural': 'Book Of The Day',
            },
        ),
    ]
