# Generated by Django 5.0.4 on 2024-04-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ipaddress_book_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='hits',
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
