# Generated by Django 5.0.4 on 2024-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_book_hits_delete_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Quote Of The Day',
            },
        ),
    ]
