# Generated by Django 5.0.4 on 2024-04-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_article_category_alter_article_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decsription', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
